<?php
$goodbye = "";

function greetings_menu(){
    $items['hello_user'] = array(
    'title' => "Hi!",
    'page callback' => 'login_splash',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    );

    $items['goodbye_user'] = array(
        'title' => "Bye!",
        'page callback' => 'logout_splash',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}


function login_splash(){
//global var produces WSOD - how to use session to set right
//    $goodbye = "bye";
    //admin
    if (user_has_role(3)) {
//       $goodbye = 'Bye Bye Bye';
        return "<p> Welcome to the Admin View! </p>";
        //VIP
    } elseif (user_has_role(5)) {
//        $goodbye = 'Peace, Love, and Cookie Cat';
        return " <p>Welcome, You Awesome Person!</p>";
        //weirdo
    } elseif (user_has_role(4)) {
//        $goodbye = 'Remember the Truth is Out There';
        return "<p>Keep your eyes open for Rock People.  Remember when it doubt, give them a spray.</p>";
        //authenticated user
    } elseif (user_has_role(2)) {
//        $goodbye = 'Come back soon!';
        return"<p>Nice to see you!</p>";
    }
//    $_SESSION['goodbye_message'] = $goodbye;
}

function logout_splash(){
//    $goodbye_message =  $_SESSION['goodbye_message'];
//    return '<p>'. $goodbye_message. '</p>';
////    //works
//    return "<p> Bye! </p>";
// //whie screen but message stays after
//
    //

    //all WSOD
//   //admin
//   if(user_has_role(3)){
//       drupal_set_message("Bye Bye Bye");
//       //VIP
//   } elseif(user_has_role(5)){
//       drupal_set_message("Peace, Love, and Cookie Cat");
//       //weirdo
//   } elseif(user_has_role(4)){
//       drupal_set_message("Remember the Truth is Out There");
//       ////authenticated user
//   }elseif(user_has_role(2)) {
//       drupal_set_message("Come back soon!");
//   }
}

//ERROR _ missing $user b/c logged out? how to pass user before logout happens

function greetings_user_login($account, $user){
        $_GET['destination'] = 'hello_user';
}

function greetings_user_logout($account){

        $_GET['destination'] = 'goodbye_user';
}


//user and account are NOT the same.  $user has array of roles, account does not ,remvoing $user gets rid of error but still WSOD
